#!/bin/bash

gstatus=`git status --porcelain`

if [ ${#gstatus} -ne 0 ]
then

	git add --all
	git commit -m "Automated sync: $gstatus"
	git pull --rebase
	git push
	expect "Username for 'https://github.com':"
	send "b06502002\r"
	expect "Password for 'https://b06502002@github.com':"
	send "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\r"
	
fi
